In [1]:
from fastai.imports import *

In [51]:
data = pd.read_excel('Randomised HHs_East.xls')

In [47]:
data.tail()

,district,subcounty,parish_t,village,hhid,hhh_full_name,HH_Contact,HHHeadship
4153,Kagadi,Rugashari,Yorodani,Yorodani_B,KAG-YOR-BEA-F-31144,Beata Mukandayambaje,99.0,Female Headed
4154,Kagadi,Rugashari,Yorodani,Yorodani_B,KAG-YOR-LOL-M-31151,Lollen Tumwesigye,773689994.0,Male Headed
4155,Kagadi,Rugashari,Yorodani,Yorodani_B,KAG-YOR-MUJ-M-31714,Mujuni Byabasheija,99.0,Male Headed
4156,Kagadi,Rugashari,Yorodani,Yorodani_B,KAG-YOR-ALO-M-31118,Aloise Kwizera,99.0,Male Headed
4157,Kagadi,Rugashari,Yorodani,Yorodani_B,KAG-YOR-JUL-F-30949,Juliet Kyirihanga,777910682.0,Female Headed

In [48]:
data.head()

,district,subcounty,parish_t,village,hhid,hhh_full_name,HH_Contact,HHHeadship
0,Kiryandongo,Mboira,Apodorwa,Abira,KIR-ABI-FRE-M-112403,Fred Meuva,99.0,Youth
1,Kiryandongo,Mboira,Apodorwa,Abira,KIR-ABI-FRA-M-151217,Francis Wedunga,993.0,Youth
2,Kiryandongo,Mboira,Apodorwa,Abira,KIR-ABI-GOF-M-144110,Gofrey Nguma,99.0,Youth
3,Kiryandongo,Mboira,Apodorwa,Abira,KIR-ABI-ROB-M-125412,Robert Okello,760126921.0,Youth
4,Kiryandongo,Mboira,Apodorwa,Abira,KIR-ABI-TAM-F-155045,Tamara Agenorwoth,99.0,Youth

In [11]:
data.shape

(4158, 8)

In [4]:
data['HHHeadship'].value_counts()

HHHeadship
Male Headed      2170
Youth             775
Female Headed     773
Name: count, dtype: int64

In [5]:
data['village'].value_counts()

village
Kasaba_A           235
Mparo_A            200
Kasaba_T/C          74
Nyabwegyereka_B     27
Abira               24
                  ...
Kiguuza             24
Kihooka             24
Kihuura_Central     24
Yorodani_B          24
Bihanga             22
Name: count, Length: 155, dtype: int64

In [73]:
from collections import defaultdict

def assign_status(group):
    count = defaultdict(int)  # To keep track of counts so far for each category
    status = []

    for idx, row in group.iterrows():
        cat = row['HHHeadship']

        if cat not in targets or cat not in reserves:
            status.append('unknown')
            continue

        count[cat] += 1

        if count[cat] <= targets[cat]:
            status.append('target')
        elif count[cat] <= targets[cat] + reserves[cat]:
            status.append('reserve')
        else:
            status.append('exceed')

    group['status'] = status
    return group

In [74]:
df = data.groupby('village', group_keys=False).apply(assign_status)

In [75]:
df

,district,subcounty,parish_t,village,hhid,hhh_full_name,HH_Contact,HHHeadship,status
0,Kaliro,Gadumire,Butambala,Bubalala,KAL-BUB-BEN-M-4198,Benard Nseko,776224915,Youth,target
1,Kaliro,Gadumire,Butambala,Bubalala,KAL-BUB-JOE-M-3054,joel Sande,789223385,Youth,target
2,Kaliro,Gadumire,Butambala,Bubalala,KAL-BUB-ZAI-M-47151,Zaire Nkalanguke,777889187,Youth,target
3,Kaliro,Gadumire,Butambala,Bubalala,KAL-BUB-DER-M-47146,Derrick Mazige,779832619,Youth,reserve
4,Kaliro,Gadumire,Butambala,Bubalala,KAL-BUB-DEN-M-3071,denis nabeta,787233269,Youth,reserve
...,...,...,...,...,...,...,...,...,...
1075,Kaliro,Gadumire,Isaalo,Ruhunga,KAL-LUH-GRA-M-3627,Grace Magino,77482812,Male Headed,reserve
1076,Kaliro,Gadumire,Isaalo,Ruhunga,KAL-LUH-PAT-M-3611,Patrick Kyabire,789387739,Male Headed,reserve
1077,Kaliro,Gadumire,Isaalo,Ruhunga,KAL-LUH-YON-M-3690,Yona Wavamuno,777089765,Male Headed,reserve
1078,Kaliro,Gadumire,Isaalo,Ruhunga,KAL-LUH-SIL-M-4080,Silas Twooli,780994434,Male Headed,reserve
1079,Kaliro,Gadumire,Isaalo,Ruhunga,KAL-LUH-LIV-M-3658,Livingston Kagumba,783452480,Male Headed,reserve

In [77]:
data.shape, df.shape

((1080, 8), (1080, 9))

In [ ]:
from fastai.imports import *

data = pd.read_excel('Randomised HHs_East.xls')

data.tail()

data.head()

data.shape

data['HHHeadship'].value_counts()

data['village'].value_counts()

from collections import defaultdict

def assign_status(group):
    count = defaultdict(int)  # To keep track of counts so far for each category
    status = []

    for idx, row in group.iterrows():
        cat = row['HHHeadship']

        if cat not in targets or cat not in reserves:
            status.append('unknown')
            continue

        count[cat] += 1

        if count[cat] <= targets[cat]:
            status.append('target')
        elif count[cat] <= targets[cat] + reserves[cat]:
            status.append('reserve')
        else:
            status.append('exceed')

    group['status'] = status
    return group



df = data.groupby('village', group_keys=False).apply(assign_status)

df

data.shape, df.shape